version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(thread)d - %(message)s'
  standard:
    format: '%(asctime)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s'
  json:
    class: 'libs.logger.JsonFormatter'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  app:
    backupCount: 7
    level: INFO
    interval: 1
    when: midnight
    filename: logs/app.log
    formatter: standard
    class: logging.handlers.TimedRotatingFileHandler
    encoding: utf-8
  json:
    backupCount: 7
    level: INFO
    interval: 1
    when: midnight
    filename: logs/json.log
    formatter: json
    class: logging.handlers.TimedRotatingFileHandler
    encoding: utf-8
root:
  level: DEBUG
  handlers: [console, app]
loggers:
  json:
    level: DEBUG
    handlers: [json]
    propagate: false
